In [3]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 14 18:46:55 2018
@author: savio

"""

import pandas as pd
import numpy as np
import xarray as xr
from netCDF4 import Dataset

## Pandas : Implemenatation

In [4]:
mod03_name = '/Users/saviosebastian/Documents/Project/CMAC/MYD03.A2002185.0000.061.2017362174430.hdf'
mod06_name = '/Users/saviosebastian/Documents/Project/CMAC/MYD06_L2.A2002185.0000.061.2018003215042.hdf'
print(mod03_name)
print(mod06_name)

/Users/saviosebastian/Documents/Project/CMAC/MYD03.A2002185.0000.061.2017362174430.hdf
/Users/saviosebastian/Documents/Project/CMAC/MYD06_L2.A2002185.0000.061.2018003215042.hdf

In [5]:
rootgrp = Dataset(mod03_name, "r", format="NETCDF3")
latitude = rootgrp.variables["Latitude"][:,:] 
longitude = rootgrp.variables["Longitude"][:,:]

rootgrp1 = Dataset(mod06_name, "r", format="NETCDF3")
cloud_mask_allbytes = rootgrp1.variables["Cloud_Mask_1km"][:,:,:]

In [6]:
londf=pd.DataFrame(np.array(longitude).byteswap().newbyteorder())
latdf=pd.DataFrame(np.array(latitude).byteswap().newbyteorder())

cat = np.asarray(cloud_mask_allbytes)
samcat = cat[:][:][:]
samcatran = samcat.transpose(2,0,1).reshape(3,-1)
samcatran2 = samcat.transpose(2,0,1)
s3 = samcatran2[:][:][0]
df34 = pd.DataFrame(s3)
catdf=pd.DataFrame(np.array(df34).byteswap().newbyteorder())

In [7]:
londfstack = londf.stack()
latdfstack = latdf.stack()
catdfstack = catdf.stack()

maindf = pd.DataFrame()

In [8]:
maindf['Latitude'] = latdfstack
maindf['Longitude'] = londfstack
maindf['CloudFraction'] = catdfstack
maindf['Latitude-Int'] = maindf.Latitude.astype(np.int16)
maindf['Longitude-Int'] = maindf.Longitude.astype(np.int16)

In [9]:
maindf

             Latitude   Longitude  CloudFraction  Latitude-Int  Longitude-Int
0    0    -999.000000 -999.000000              0          -999           -999
     1    -999.000000 -999.000000              0          -999           -999
     2    -999.000000 -999.000000              0          -999           -999
     3    -999.000000 -999.000000              0          -999           -999
     4    -999.000000 -999.000000              0          -999           -999
     5    -999.000000 -999.000000              0          -999           -999
     6    -999.000000 -999.000000              0          -999           -999
     7    -999.000000 -999.000000              0          -999           -999
     8    -999.000000 -999.000000              0          -999           -999
     9    -999.000000 -999.000000              0          -999           -999
     10   -999.000000 -999.000000              0          -999           -999
     11   -999.000000 -999.000000              0          -999           -999
     12   -999.000000 -999.000000              0          -999           -999
     13   -999.000000 -999.000000              0          -999           -999
     14   -999.000000 -999.000000              0          -999           -999
     15   -999.000000 -999.000000              0          -999           -999
     16   -999.000000 -999.000000              0          -999           -999
     17   -999.000000 -999.000000              0          -999           -999
     18   -999.000000 -999.000000              0          -999           -999
     19   -999.000000 -999.000000              0          -999           -999
     20   -999.000000 -999.000000              0          -999           -999
     21   -999.000000 -999.000000              0          -999           -999
     22   -999.000000 -999.000000              0          -999           -999
     23   -999.000000 -999.000000              0          -999           -999
     24   -999.000000 -999.000000              0          -999           -999
     25   -999.000000 -999.000000              0          -999           -999
     26   -999.000000 -999.000000              0          -999           -999
     27   -999.000000 -999.000000              0          -999           -999
     28   -999.000000 -999.000000              0          -999           -999
     29   -999.000000 -999.000000              0          -999           -999
...               ...         ...            ...           ...            ...
2039 1324   26.891554   37.187840            -73            26             37
     1325   26.882595   37.226582            -73            26             37
     1326   26.873573   37.265549            -73            26             37
     1327   26.864296   37.305557            -73            26             37
     1328   26.854782   37.346531            -73            26             37
     1329   26.845901   37.384727            -73            26             37
     1330   26.837509   37.420780            -73            26             37
     1331   26.828480   37.459518            -73            26             37
     1332   26.819075   37.499805            -73            26             37
     1333   26.809587   37.540398            -73            26             37
     1334   26.800318   37.580002            -73            26             37
     1335   26.791092   37.619366            -73            26             37
     1336   26.781834   37.658813            -73            26             37
     1337   26.772379   37.699039            -73            26             37
     1338   26.761997   37.743141            -73            26             37
     1339   26.751890   37.786026            -73            26             37
     1340   26.740446   37.834488            -73            26             37
     1341   26.729702   37.879925            -73            26             37
     1342   26.719481   37.923080            -73            26             37
     1343   26.709538   37.965008            -73            26             37
     1344   26.699255   38.008301            -73            26             38
     1345   26.688856   38.052025            -73            26             38
     1346   26.679001   38.093395            -73            26             38
     1347   26.668844   38.135979            -73            26             38
     1348   26.658104   38.180939            -73            26             38
     1349   26.647142   38.226757            -73            26             38
     1350   26.636370   38.271709            -73            26             38
     1351   26.625828   38.315639            -73            26             38
     1352   26.614887   38.361156            -73            26             38
     1353   26.603619   38.407970            -73            26             38

[2762160 rows x 5 columns]

In [10]:
# -- maindf.groupby(['Latitude-Int','Longitude-Int']).groups

In [11]:
#-- list(dict(maindf.groupby(['Latitude-Int','Longitude-Int']).groups))

In [12]:
maindf.groupby(['Latitude-Int','Longitude-Int']).mean()

                              Latitude   Longitude  CloudFraction
Latitude-Int Longitude-Int
-999         -999          -999.000000 -999.000000       0.000000
 26           36             26.976418   36.891617     -73.000000
              37             26.906858   37.611652     -73.000000
              38             26.844639   38.263233     -73.000000
 27           31             27.992493   31.959021     -73.000000
              32             27.931532   32.633694     -73.000000
              33             27.845177   33.543140       5.644872
              34             27.747877   34.522259      45.561687
              35             27.646114   35.513016      -0.134935
              36             27.541477   36.503662     -73.005994
              37             27.504074   37.486988     -73.000000
              38             27.542635   38.380779     -73.002174
 28           25             28.988077   25.910423     -73.000000
              26             28.937803   26.610983     -73.000000
              27             28.868759   27.547142     -73.000000
              28             28.792873   28.526911     -73.000000
              29             28.712524   29.516136     -73.000000
              30             28.628630   30.509109     -52.952189
              31             28.541912   31.503819     -71.991074
              32             28.503096   32.485409     -56.140130
              33             28.503889   33.489334     -21.144345
              34             28.505531   34.490280     -17.877921
              35             28.501595   35.484806     -68.293527
              36             28.504019   36.489174     -72.773184
              37             28.503534   37.486786     -73.000000
              38             28.505753   38.485802     -73.013693
              39             28.713034   39.109791     -73.244776
 29           15             29.974253   15.611496     -73.000000
              16             29.952028   16.589682     -73.000000
              17             29.926472   17.546154     -73.000000
...                                ...         ...            ...
 45           38             45.085560   38.368011      44.462647
              39             45.016399   39.074310     109.545455
 46           16             46.447960   16.923309       5.911032
              17             46.499199   17.511972      13.647698
              18             46.497883   18.510967      18.977211
              19             46.495014   19.511477       6.823482
              20             46.497726   20.509781      -2.439716
              21             46.495956   21.511299      -6.996847
              22             46.498611   22.510712     -11.931469
              23             46.495029   23.510134     -10.451237
              24             46.494801   24.509447      -7.839731
              25             46.495426   25.509317     -11.935465
              26             46.469444   26.500965      -6.320374
              27             46.420197   27.498274      -1.600618
              28             46.367550   28.494337      -0.337253
              29             46.309669   29.489159      -0.969969
              30             46.247822   30.481697      39.864289
              31             46.181179   31.469215      56.455868
              32             46.111107   32.441059      54.779128
              33             46.046066   33.289005      66.093069
 47           16             47.184685   16.953938     -14.764706
              17             47.218056   17.502096      -4.886139
              18             47.206505   18.503235      42.490909
              19             47.190979   19.504683       8.536481
              20             47.175846   20.499151       6.000000
              21             47.151241   21.498428       0.834395
              22             47.127338   22.490515       1.623104
              23             47.094662   23.473248      -7.421622
              24             47.060375   24.453926      -3.429400
              25             47.029530   25.349236      18.772727

[527 rows x 3 columns]

## XArray : Implemenatation

In [13]:
dsa = xr.Dataset()
dsa.coords['Latitude'] = (('x'), latdfstack)
dsa.coords['Longitude'] = (('x'), londfstack)
dsa['CloudFraction'] = (('x'), catdfstack)
a = maindf.Longitude.astype(np.int16)
b = maindf.Latitude.astype(np.int16)
dsa.coords['Longitude-Int'] = (('x'), a)
dsa.coords['Latitude-Int'] = (('x'), b)

In [14]:
dsa

<xarray.Dataset>
Dimensions:        (x: 2762160)
Coordinates:
    Latitude       (x) float32 -999.0 -999.0 -999.0 ... 26.614887 26.603619
    Longitude      (x) float32 -999.0 -999.0 -999.0 ... 38.361156 38.40797
    Longitude-Int  (x) int16 -999 -999 -999 -999 -999 -999 ... 38 38 38 38 38 38
    Latitude-Int   (x) int16 -999 -999 -999 -999 -999 -999 ... 26 26 26 26 26 26
Dimensions without coordinates: x
Data variables:
    CloudFraction  (x) int8 0 0 0 0 0 0 0 0 ... -73 -73 -73 -73 -73 -73 -73 -73

In [42]:
list(dsa.groupby('Latitude-Int','Longitude-Int'))

[(-999, <xarray.Dataset>
  Dimensions:        (x: 94780)
  Coordinates:
      Latitude       (x) float32 -999.0 -999.0 -999.0 ... -999.0 -999.0 -999.0
      Longitude      (x) float32 -999.0 -999.0 -999.0 ... -999.0 -999.0 -999.0
      Longitude-Int  (x) int64 -999 -999 -999 -999 -999 ... -999 -999 -999 -999
      Latitude-Int   (x) int64 -999 -999 -999 -999 -999 ... -999 -999 -999 -999
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 0 0 0 0 0 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0),
 (26, <xarray.Dataset>
  Dimensions:        (x: 800)
  Coordinates:
      Latitude       (x) float32 26.998667 26.992504 ... 26.614887 26.603619
      Longitude      (x) float32 38.548954 38.49679 ... 38.361156 38.40797
      Longitude-Int  (x) int64 38 38 38 38 38 38 38 38 ... 38 38 38 38 38 38 38 38
      Latitude-Int   (x) int64 26 26 26 26 26 26 26 26 ... 26 26 26 26 26 26 26 26
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... -73 -73 -73 -73 -73 -73),
 (27, <xarray.Dataset>
  Dimensions:        (x: 14738)
  Coordinates:
      Latitude       (x) float32 27.98997 27.995426 ... 27.01267 27.004942
      Longitude      (x) float32 38.92651 38.827927 ... 36.658783 36.692837
      Longitude-Int  (x) int64 38 38 38 38 38 38 38 38 ... 36 36 36 36 36 36 36 36
      Latitude-Int   (x) int64 27 27 27 27 27 27 27 27 ... 27 27 27 27 27 27 27 27
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... -73 -73 -73 -73 -73 -73),
 (28, <xarray.Dataset>
  Dimensions:        (x: 55769)
  Coordinates:
      Latitude       (x) float32 28.997799 28.994564 ... 28.004723 28.001755
      Longitude      (x) float32 39.313507 39.252842 ... 31.878868 31.894638
      Longitude-Int  (x) int64 39 39 39 39 39 39 39 39 ... 31 31 31 31 31 31 31 31
      Latitude-Int   (x) int64 28 28 28 28 28 28 28 28 ... 28 28 28 28 28 28 28 28
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... -73 -73 -73 -73 -73 -73),
 (29, <xarray.Dataset>
  Dimensions:        (x: 124445)
  Coordinates:
      Latitude       (x) float32 29.988184 29.99446 ... 29.001839 29.000406
      Longitude      (x) float32 39.700535 39.600033 39.6469 ... 25.75105 25.76153
      Longitude-Int  (x) int64 39 39 39 39 39 39 39 39 ... 25 25 25 25 25 25 25 25
      Latitude-Int   (x) int64 29 29 29 29 29 29 29 29 ... 29 29 29 29 29 29 29 29
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... -73 -73 -73 -73 -73 -73),
 (30, <xarray.Dataset>
  Dimensions:        (x: 153159)
  Coordinates:
      Latitude       (x) float32 30.992218 30.999184 ... 30.003368 30.00092
      Longitude      (x) float32 40.107468 40.005886 ... 15.06392 15.112411
      Longitude-Int  (x) int64 40 40 40 40 39 40 40 40 ... 15 15 15 15 15 15 15 15
      Latitude-Int   (x) int64 30 30 30 30 30 30 30 30 ... 30 30 30 30 30 30 30 30
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... -73 -73 -73 -73 -73 -73),
 (31, <xarray.Dataset>
  Dimensions:        (x: 153263)
  Coordinates:
      Latitude       (x) float32 31.992876 31.988144 ... 31.005383 31.002613
      Longitude      (x) float32 40.52994 40.475353 ... 15.336277 15.384951
      Longitude-Int  (x) int64 40 40 40 40 40 40 40 40 ... 15 15 15 15 15 15 15 15
      Latitude-Int   (x) int64 31 31 31 31 31 31 31 31 ... 31 31 31 31 31 31 31 31
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... -73 -73 -73 -73 -73 -73),
 (32, <xarray.Dataset>
  Dimensions:        (x: 153387)
  Coordinates:
      Latitude       (x) float32 32.991245 32.99169 ... 32.003414 32.00069
      Longitude      (x) float32 40.96533 40.961456 ... 15.364527 15.414462
      Longitude-Int  (x) int64 40 40 40 40 40 40 40 40 ... 15 15 15 15 15 15 15 15
      Latitude-Int   (x) int64 32 32 32 32 32 32 32 32 ... 32 32 32 32 32 32 32 32
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 ... 117 115 -73 117 117 115),
 (33, <xarray.Dataset>
  Dimensions:        (x: 153453)
  Coordinates:
      Latitude       (x) float32 33.988037 33.996502 ... 33.00362 33.001175
      Longitude      (x) float32 41.408257 41.303417 ... 15.65183 15.701197
      Longitude-Int  (x) int64 41 41 41 41 41 41 41 41 ... 16 15 15 15 15 15 15 15
      Latitude-Int   (x) int64 33 33 33 33 33 33 33 33 ... 33 33 33 33 33 33 33 33
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 -73 ... 49 49 49 49 49 49 49),
 (34, <xarray.Dataset>
  Dimensions:        (x: 153600)
  Coordinates:
      Latitude       (x) float32 34.999775 34.995796 ... 34.00272 34.000336
      Longitude      (x) float32 41.872818 41.816242 ... 15.578274 15.629779
      Longitude-Int  (x) int64 41 41 41 41 41 41 41 41 ... 15 15 15 15 15 15 15 15
      Latitude-Int   (x) int64 34 34 34 34 34 34 34 34 ... 34 34 34 34 34 34 34 34
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -73 -73 ... 49 49 49 49 49 49 49),
 (35, <xarray.Dataset>
  Dimensions:        (x: 153695)
  Coordinates:
      Latitude       (x) float32 35.991486 35.988007 ... 35.00356 35.001156
      Longitude      (x) float32 42.344852 42.287167 ... 15.907383 15.957961
      Longitude-Int  (x) int64 42 42 42 42 42 42 42 42 ... 15 15 15 15 15 15 15 15
      Latitude-Int   (x) int64 35 35 35 35 35 35 35 35 ... 35 35 35 35 35 35 35 35
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -77 -77 -75 -73 -75 -75 -75 ... 49 49 49 49 49 49 49),
 (36, <xarray.Dataset>
  Dimensions:        (x: 153758)
  Coordinates:
      Latitude       (x) float32 36.997635 36.984528 ... 36.002293 36.000244
      Longitude      (x) float32 42.767845 42.81595 ... 15.827412 15.8802595
      Longitude-Int  (x) int64 42 42 42 42 42 42 42 42 ... 16 16 16 16 16 15 15 15
      Latitude-Int   (x) int64 36 36 36 36 36 36 36 36 ... 36 36 36 36 36 36 36 36
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -73 -73 -73 -73 -73 -75 -75 ... 49 49 49 49 49 49 49),
 (37, <xarray.Dataset>
  Dimensions:        (x: 153852)
  Coordinates:
      Latitude       (x) float32 37.999107 37.998447 ... 37.00294 37.000874
      Longitude      (x) float32 43.28393 43.217472 ... 16.10766 16.159971
      Longitude-Int  (x) int64 43 43 43 43 43 43 43 43 ... 16 16 15 15 16 16 16 16
      Latitude-Int   (x) int64 37 37 37 37 37 37 37 37 ... 37 37 37 37 37 37 37 37
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -9 -73 -9 -11 -9 -9 -9 -9 ... 49 49 49 49 49 49 49),
 (38, <xarray.Dataset>
  Dimensions:        (x: 154036)
  Coordinates:
      Latitude       (x) float32 38.998695 38.993427 ... 38.002323 38.000755
      Longitude      (x) float32 43.81189 43.762516 ... 16.021412 16.065182
      Longitude-Int  (x) int64 43 43 43 43 43 43 43 43 ... 16 16 16 16 16 16 16 16
      Latitude-Int   (x) int64 38 38 38 38 38 38 38 38 ... 38 38 38 38 38 38 38 38
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -9 -9 -9 -9 -9 -9 -11 -9 ... 49 49 49 49 49 -9 119),
 (39, <xarray.Dataset>
  Dimensions:        (x: 154170)
  Coordinates:
      Latitude       (x) float32 39.98691 39.999718 ... 39.003468 39.001556
      Longitude      (x) float32 44.38649 44.27357 ... 16.306684 16.366138
      Longitude-Int  (x) int64 44 44 44 44 44 44 44 44 ... 16 16 16 16 16 16 16 16
      Latitude-Int   (x) int64 39 39 39 39 39 39 39 39 ... 39 39 39 39 39 39 39 39
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -15 -15 -15 -15 -15 -15 -15 ... -9 49 115 -11 -9 -9),
 (40, <xarray.Dataset>
  Dimensions:        (x: 154386)
  Coordinates:
      Latitude       (x) float32 40.98733 40.985672 ... 40.001972 40.00019
      Longitude      (x) float32 44.923615 44.86234 ... 16.674582 16.727575
      Longitude-Int  (x) int64 44 44 44 44 44 44 44 44 ... 16 16 16 16 16 16 16 16
      Latitude-Int   (x) int64 40 40 40 40 40 40 40 40 ... 40 40 40 40 40 40 40 40
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -13 -9 -13 -9 -9 -9 -13 ... -15 -15 113 113 49 49),
 (41, <xarray.Dataset>
  Dimensions:        (x: 154615)
  Coordinates:
      Latitude       (x) float32 41.985382 41.984673 ... 41.002167 41.00052
      Longitude      (x) float32 45.542835 45.478477 ... 16.517776 16.572868
      Longitude-Int  (x) int64 45 45 45 45 45 45 45 45 ... 17 17 17 16 16 16 16 16
      Latitude-Int   (x) int64 41 41 41 41 41 41 41 41 ... 41 41 41 41 41 41 41 41
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -15 -15 -15 -15 -15 -15 ... -15 -15 -15 -15 -15 -15),
 (42, <xarray.Dataset>
  Dimensions:        (x: 154566)
  Coordinates:
      Latitude       (x) float32 42.991234 42.990284 ... 42.00221 42.000744
      Longitude      (x) float32 46.142742 46.07955 ... 16.901028 16.95572
      Longitude-Int  (x) int64 46 46 46 46 46 46 45 46 ... 16 16 16 16 16 16 16 16
      Latitude-Int   (x) int64 42 42 42 42 42 42 42 42 ... 42 42 42 42 42 42 42 42
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -15 -15 -15 -15 -15 -15 -15 ... 49 49 49 49 49 49 49),
 (43, <xarray.Dataset>
  Dimensions:        (x: 151927)
  Coordinates:
      Latitude       (x) float32 43.990948 43.981102 ... 43.001667 43.00041
      Longitude      (x) float32 43.51958 43.55797 ... 16.548317 16.60741
      Longitude-Int  (x) int64 43 43 43 43 43 43 43 43 ... 17 17 17 17 17 17 16 16
      Latitude-Int   (x) int64 43 43 43 43 43 43 43 43 ... 43 43 43 43 43 43 43 43
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 113 113 113 113 113 113 ... 113 113 113 113 49 49),
 (44, <xarray.Dataset>
  Dimensions:        (x: 139342)
  Coordinates:
      Latitude       (x) float32 44.99981 44.99522 44.990612 ... 44.00239 44.00098
      Longitude      (x) float32 39.20526 39.226902 ... 17.029327 17.087372
      Longitude-Int  (x) int64 39 39 39 39 39 39 39 39 ... 16 16 16 16 16 16 17 17
      Latitude-Int   (x) int64 44 44 44 44 44 44 44 44 ... 44 44 44 44 44 44 44 44
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 117 117 119 119 119 119 119 ... -9 -9 -11 -13 -13 -9),
 (45, <xarray.Dataset>
  Dimensions:        (x: 112687)
  Coordinates:
      Latitude       (x) float32 45.999195 45.99707 ... 45.002308 45.001072
      Longitude      (x) float32 33.846466 33.85959 ... 17.504559 17.56006
      Longitude-Int  (x) int64 33 33 33 33 33 33 33 33 ... 17 17 17 17 17 17 17 17
      Latitude-Int   (x) int64 45 45 45 45 45 45 45 45 ... 45 45 45 45 45 45 45 45
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 117 117 117 117 115 115 ... -13 -13 -13 -13 -9 -9),
 (46, <xarray.Dataset>
  Dimensions:        (x: 60872)
  Coordinates:
      Latitude       (x) float32 46.99919 46.99746 ... 46.001656 46.000713
      Longitude      (x) float32 25.95709 25.976044 25.99565 ... 17.021 17.08061
      Longitude-Int  (x) int64 25 25 25 26 26 26 26 26 ... 17 17 17 16 16 16 17 17
      Latitude-Int   (x) int64 46 46 46 46 46 46 46 46 ... 46 46 46 46 46 46 46 46
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 115 115 115 115 115 115 ... -9 -13 -13 -13 -13 -13),
 (47, <xarray.Dataset>
  Dimensions:        (x: 6860)
  Coordinates:
      Latitude       (x) float32 47.47121 47.470352 ... 47.002144 47.00102
      Longitude      (x) float32 16.955399 17.018963 ... 17.59178 17.64939
      Longitude-Int  (x) int64 16 17 17 17 17 17 17 17 ... 17 17 17 17 17 17 17 17
      Latitude-Int   (x) int64 47 47 47 47 47 47 47 47 ... 47 47 47 47 47 47 47 47
  Dimensions without coordinates: x
  Data variables:
      CloudFraction  (x) int8 -15 113 113 113 113 113 ... -15 -15 -15 -13 -13 -11)]

In [15]:
XDict = dict(list(dsa.groupby('Latitude-Int','Longitude-Int')))

In [16]:
for items in XDict:
    print (XDict[items].mean())

<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 0.0
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -73.0
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -33.37
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -58.79
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -66.57
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -61.45
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -3.417
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 28.0
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 37.46
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 37.22
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 35.0
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 25.89
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 6.106
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 3.978
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 -0.2462
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 7.887
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 18.62
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 32.24
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 27.54
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 28.14
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 23.14
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 4.725
<xarray.Dataset>
Dimensions:        ()
Data variables:
    CloudFraction  float64 6.451

In [17]:
#--Masked Arrays
#----Masked arrays are arrays that may have missing or invalid entries. 
#----The numpy.ma module provides a nearly work-alike replacement for numpy that supports data arrays with masks.

#--Rationale
#----n many circumstances, datasets can be incomplete or tainted by the presence of invalid data. 
#----For example, a sensor may have failed to record a data, or recorded an invalid value. 
#----The numpy.ma module provides a convenient way to address this issue, by introducing masked arrays.

#--Accessing the Relevant Values:
latitude.shape

(2040, 1354)

In [21]:
latitude

masked_array(
  data=[[--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        ...,
        [30.023902893066406, 30.0213565826416, 30.018844604492188, ...,
         26.660354614257812, 26.649608612060547, 26.63867950439453],
        [30.005863189697266, 30.003368377685547, 30.000919342041016, ...,
         26.643115997314453, 26.632293701171875, 26.621292114257812],
        [29.987855911254883, 29.985397338867188, 29.982986450195312, ...,
         26.62582778930664, 26.614887237548828, 26.603618621826172]],
  mask=[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],
  fill_value=-999.0,
  dtype=float32)

In [18]:
latitude[~latitude.mask][:]

masked_array(data=[47.47121047973633, 47.47035217285156,
                   47.469459533691406, ..., 26.62582778930664,
                   26.614887237548828, 26.603618621826172],
             mask=[False, False, False, ..., False, False, False],
       fill_value=-999.0,
            dtype=float32)

In [19]:
d1 = latitude[~latitude.mask][:]
len(d1)

2667380

In [20]:
#---Getting All the Relevant Data From the Array(Masked = FALSE)
latitude.compressed()

array([47.47121 , 47.470352, 47.46946 , ..., 26.625828, 26.614887,
       26.603619], dtype=float32)

In [ ]:
#----To get rid of the Mask completely form the Dataframe.
x.mask = ma.nomask